export const CHATHISTORY_REQUEST = 'ChatHistory/CHATHISTORY_REQUEST';
export const CHATHISTORY_SUCCESS = 'ChatHistory/CHATHISTORY_SUCCESS';
export const CHATHISTORY_FAILURE = 'ChatHistory/CHATHISTORY_FAILURE';
