const Images = {
  loaderGif: require('../../assets/icon/eatsLoader.gif'),
  loginLogo: require('../../assets/icon/loginBglogo.png'),
  fbLogo: require('../../assets/icon/icon_fb.png'),
  gmailLogo: require('../../assets/icon/icon_gplus.png'),
  loginBanner: require('../../assets/icon/MaskGroup.png'),
  appleLogo: require('../../assets/icon/icon_apple.png'),
  nextIcon: require('../../assets/icon/nextt.png'),
  backImage: require('../../assets/icon/back.png'),
  nameIcon: require('../../assets/icon/myprofile.png'),
  mailIcon: require('../../assets/icon/email.png'),
  passwordIcon: require('../../assets/icon/password.png'),
  locationIcon: require('../../assets/icon/blacloac.png'),
  registerBGIcon: require('../../assets/icon/loginBg.png'),
  lockKeyIcon: require('../../assets/icon/pass_key.png'),
  starFilled: require('../../assets/icon/starFilled.png'),
  starEmpty: require('../../assets/icon/starGr.png'),
  addImage: require('../../assets/icon/add.png'),
  MarkUPIcon: require('../../assets/icon/location.png'),
  dummyUser: require('../../assets/icon/dummyUser.png'),
  phoneIcon: require('../../assets/icon/call.png'),
  crossIcon: require('../../assets/icon/cross.png'),
  sucessIcon: require('../../assets/icon/tick.png'),
  menuIcon: require('../../assets/icon/menu_icon.png'),
  profileBackground: require('../../assets/icon/profilebackground.png'),
  closeImage: require('../../assets/icon/myclose.png'),
  discountIcon: require('../../assets/icon/discount.png'),
  homeTickIcon: require('../../assets/icon/homeselect.png'),
  rightarrow: require('../../assets/icon/rightarrow.png'),
  greenTick: require('../../assets/icon/greenTick.png'),
  plusIcon: require('../../assets/icon/plus.png'),
  deleteIcon: require('../../assets/icon/dlt.png'),
  cardLogo: require('../../assets/icon/cardBG.png'),
  cardIcon: require('../../assets/icon/red_card.png'),
  trackIcon: require('../../assets/icon/track.png'),
  inviteIcon: require('../../assets/icon/invite.png'),
  thankYouIcon: require('../../assets/icon/thankyou.png'),
  filterIcon: require('../../assets/icon/Filter.png'),
  nearByIcon: require('../../assets/icon/NearBy.png'),
  greenRatingIcon: require('../../assets/icon/greenRating.png'),
  splashIcon: require('../../assets/icon/splash.png'),
  invite_friend: require('../../assets/icon/invite_friend.png'),
  helpIcon: require('../../assets/icon/help.png'),
  EllipseIcon: require('../../assets/icon/Ellipse.png'),
  box_green: require('../../assets/icon/box_green.png'),
  starBlank: require('../../assets/icon/grey-star.png'),
  StarSmile: require('../../assets/icon/StarSmile.png'),
  innovationIcon: require('../../assets/icon/innovation.png'),
  redBackgroundIcon: require('../../assets/icon/redBackground.png'),
  greenSucessIcon: require('../../assets/icon/success.png'),
  rateIcon: require('../../assets/icon/rate.png'),
  arrowUp: require('../../assets/icon/arrowUp.png'),
  dropDownArrow: require('../../assets/icon/drop_down.png'),
  driverTopIcon: require('../../assets/icon/driverbiketop.png'),
  listCall: require('../../assets/icon/ListCall.png'),
  listScooterIcon: require('../../assets/icon/listScooter.png'),
  listRateIcon: require('../../assets/icon/listRate.png'),
  promoCodeImage: require('../../assets/icon/promoimg.png'),
  cancel: require('../../assets/icon/cancel.png'),

  icForkKnife: require('../../assets/icon/forkKnife.png'),
  icCash: require('../../assets/icon/cash.png'),
  icReorder: require('../../assets/icon/reorder.png'),
  icPencil: require('../../assets/icon/pencil.png'),
  icCardBin: require('../../assets/icon/trashCanBlack.png'),
  icAddOnCheck: require('../../assets/icon/addOnCheck.png'),
  icAddOnUncheck: require('../../assets/icon/addOnUncheck.png'),
  icEyeCrossed: require('../../assets/icon/eyeCrossed.png'),
  icLocation: require('../../assets/icon/location.png'),
  icShoppingBox: require('../../assets/icon/shoppingBox.png'),
  icReverseTriangle: require('../../assets/icon/reverseTriangle.png'),
  icEyeOpened: require('../../assets/icon/eyeOpened.png'),
  icCheckedRound: require('../../assets/icon/roundChecked.png'),
  icUncheckedRound: require('../../assets/icon/roundUnchecked.png'),
  icTargetLocation: require('../../assets/icon/icTargetLocation.png'),
  icEditProfile: require('../../assets/icon/icEditProfile.png'),
  icStickArrowRight: require('../../assets/icon/stickArrowRight.png'),
  icAssistance: require('../../assets/icon/assistance.png'),
  icUploadMsg: require('../../assets/icon/uploadMsgMedia.png'),
  icSendMsg: require('../../assets/icon/sendMsg.png'),
  icRedeemMinus: require('../../assets/icon/icRedeemMinus.png'),
  icEarnedPlus: require('../../assets/icon/icEarnedPlus.png'),
  icCamera: require('../../assets/icon/icCamera.png'),
  icChat: require('../../assets/icon/icChat.png'),
  icGiftCheck: require('../../assets/icon/icGiftCheck.png'),
  icGiftUncheck: require('../../assets/icon/icGiftUncheck.png'),
  icLangUsa: require('../../assets/icon/icLangUsa.png'),
  icLangUae: require('../../assets/icon/icLangUae.png'),
  icCopy: require('../../assets/icon/icCopy.png'),

  //  ** IC tab bar ** //
  icTabBarSearch: require('../../assets/icon/dashicons_search.png'),
  icTabBarOrder: require('../../assets/icon/bx_bxs-detail.png'),
  icTabBarCart: require('../../assets/icon/gridicons_cart.png'),
  icTabBarProfile: require('../../assets/icon/Vector.png'),
  icTabBarActiveHome: require('../../assets/icon/activeHome.png'),
  icTabBarInactiveHome: require('../../assets/icon/home-grey.png'),

  //  ** IC menu bar ** //
  icMenuBarHome: require('../../assets/icon/fluent_home-16-filled.png'),
  icMenuBarInviteFriends: require('../../assets/icon/inviteFriends.png'),
  icMenuBarMyAddress: require('../../assets/icon/fluent_location-48-filled.png'),
  icMenuBarMyWallet: require('../../assets/icon/icMyWallet.png'),
  icMenuBarGiftCard: require('../../assets/icon/icGiftCard.png'),
  icMenuBarPaymentMethod: require('../../assets/icon/fluent_payment-16-filled.png'),
  icMenuBarProfile: require('../../assets/icon/fluent_home-16-filled.png'),
  icMenuBarRefundPolicy: require('../../assets/icon/ph_note-fill.png'),
  icMenuBarAboutUs: require('../../assets/icon/bx_bxs-user.png'),
  icMenuBarContactUs: require('../../assets/icon/fluent_chat-bubbles-question-24-filled.png'),
  icMenuBarHelpNSupport: require('../../assets/icon/clarity_help-solid.png'),
  icMenuBarLogout: require('../../assets/icon/ri_logout-circle-r-fill.png'),

  // Dummy Images
  dummyBanner: require('../../assets/icon/surajdhaba.png'),
  dummyBottomCurve: require('../../assets/icon/bottomCurve.png'),
  dummyDrawer: require('../../assets/icon/drawerBg.png'),
  dummyProfilePic: require('../../assets/icon/user.png'),
  dummyBiryani: require('../../assets/icon/biryani.png'),
  downArrow: require('../../assets/icon/Down-Arrow.png'),
  // AddressPana: require('../../assets/icon/Address-pana.png'),

};
export default Images;
